DATA:
  DATASET: dogs
MODEL:
  TYPE: swin_tree
  NAME: swin_base_patch4_window7_224_22k
  DROP_PATH_RATE: 0.1
#  RESUME: '448DOGs depth 6 CTM GMP 89.36.pth'
  TREE:
    DEPTH: 6
    PROTO_SIZE: [ 2,2 ]
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 14
TRAIN:
  EPOCHS: 30
  WARMUP_EPOCHS: 1
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07